server:
  port: 8081
spring:
  application:
    name: backend-configService
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Letoesp/PreuTopEducationMicroServicesVersion
          search-paths: config-data